name: first github actions
on:
  push:
    branches:
      - main
    pull_request:
      - main
    workflow_dispatch:
env:
 IMAGE_NAME: krishnapuppala97/pk
 IMAGE_TAG: ${{github.run_id}}
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: maven installation
        run:  sudo apt install maven -y
      - name: git clone
        run: sudo git clone https://github.com/krishnapuppala97/maven-web-application.git 
      - name: build artifact
        run: |
              cd maven-web-application
              sudo mvn clean package install
      - name: Build the Docker image
        run: |
               cd maven-web-application 
               docker build . --file Dockerfile --tag  pk:12
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .maven-web-application/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pk:latest
      
       # shell: bash 
