name: first github actions
on:
  push:
    branches:
      - main
    pull_request:
      - main
    workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: java version
        run: java -version
      - name: maven installation
        run: | 
             sudo apt install maven -y
             sudo mvn -version
             sudo mkdir maven
             cd maven
             sudo git clone https://github.com/krishnapuppala97/maven-web-application.git 
             pwd |ls -l
             cd maven-web-application
    
            # mvn clean package       
             
      
      
        shell: bash 
