name: first github actions
on:
  push:
    branches:
      - main
    pull_request:
      - main
    workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'adopt'
      - name: maven installation
        run:  sudo apt install maven -y
      - name: git clone
        run: sudo git clone https://github.com/krishnapuppala97/maven-web-application.git 
      - name: build artifact
        run: |
              cd maven-web-application
              sudo mvn clean package install
         /*     
             | 
             sudo apt install maven -y
             sudo mvn -version
             sudo mkdir maven
             cd maven
             sudo git clone https://github.com/krishnapuppala97/maven-web-application.git 
             pwd |ls -l
             cd maven-web-application
    
             mvn clean package install
             
      */
      
        shell: bash 
